function RNG(seed){let s=seed>>>0;return()=>{s^=s<<13;s>>>=0;s^=s>>>17;s>>>=0;s^=s<<5;s>>>=0;return(s>>>0)/4294967296}};
function stdPipeline(n,err,fixCost,rng){let total=0;for(let i=0;i<n;i++)if(rng()<err)total+=fixCost;return total}
function tgrmPipeline(n,err,fixCost,mCost,tau,rng){let total=0,energy=0,eMax=1000;for(let i=0;i<n;i++){if(rng()<err){const size=rng();if(size<tau&&energy<eMax){total+=mCost;energy+=mCost}else{total+=fixCost;energy+=1}}}return total}
function runOnce(params,seed=42){const r1=RNG(seed),r2=RNG(seed);const std=stdPipeline(params.n,params.err,params.fix,r1);const tgrm=tgrmPipeline(params.n,params.err,params.fix,params.mc,params.tau,r2);const gain=std?((std-tgrm)/std)*100:0;return{std,tgrm,gain}}
const els={n:document.getElementById('n'),err:document.getElementById('err'),tau:document.getElementById('tau'),fix:document.getElementById('fix'),mc:document.getElementById('mc'),nOut:document.getElementById('nOut'),errOut:document.getElementById('errOut'),tauOut:document.getElementById('tauOut'),fixOut:document.getElementById('fixOut'),mcOut:document.getElementById('mcOut'),runBtn:document.getElementById('runBtn'),result:document.getElementById('result'),chart:document.getElementById('chart')};
function syncLabels(){els.nOut.textContent=(+els.n.value).toLocaleString();els.errOut.textContent=(+els.err.value).toFixed(2);els.tauOut.textContent=(+els.tau.value).toFixed(2);els.fixOut.textContent=(+els.fix.value);els.mcOut.textContent=(+els.mc.value)}['n','err','tau','fix','mc'].forEach(id=>els[id].addEventListener('input',syncLabels));syncLabels();
function currentParams(){return{n:+els.n.value,err:+els.err.value,tau:+els.tau.value,fix:+els.fix.value,mc:+els.mc.value}}
function drawChart(ctx,taus,gains){const W=ctx.canvas.width,H=ctx.canvas.height;ctx.clearRect(0,0,W,H);ctx.strokeStyle='#999';ctx.beginPath();ctx.moveTo(40,H-30);ctx.lineTo(W-10,H-30);ctx.lineTo(W-10,20);ctx.stroke();ctx.fillStyle='#666';ctx.font='12px system-ui';[0.1,0.3,0.5,0.7,0.9].forEach(t=>{ctx.fillText(t.toFixed(1),40+(W-60)*(t-0.1)/(0.8),H-12)});[0,20,40,60].forEach(g=>{ctx.fillText(g+'%',8,(H-30)-(H-60)*(g)/60+4);ctx.beginPath();ctx.moveTo(40,(H-30)-(H-60)*(g)/60);ctx.lineTo(W-10,(H-30)-(H-60)*(g)/60);ctx.strokeStyle='#eee';ctx.stroke();});
ctx.strokeStyle='#0a7';ctx.fillStyle='#0a7';ctx.beginPath();for(let i=0;i<taus.length;i++){const X=40+(W-60)*(taus[i]-0.1)/(0.8);const Y=(H-30)-(H-60)*(gains[i])/60;if(i===0)ctx.moveTo(X,Y);else ctx.lineTo(X,Y);}ctx.stroke();for(let i=0;i<taus.length;i++){const X=40+(W-60)*(taus[i]-0.1)/(0.8);const Y=(H-30)-(H-60)*(gains[i])/60;ctx.beginPath();ctx.arc(X,Y,3,0,Math.PI*2);ctx.fill();}}
els.runBtn.addEventListener('click',()=>{const p=currentParams();const {std,tgrm,gain}=runOnce(p,42);els.result.textContent=`Std: ${Math.round(std)}, TGRM: ${Math.round(tgrm)}, Gain: ${gain.toFixed(1)}%`;const taus=[],gains=[];for(let t=0.1;t<=0.9;t+=0.05){taus.push(+t.toFixed(2));const g=runOnce({...p,tau:t},42).gain;gains.push(g)};const ctx=els.chart.getContext('2d');drawChart(ctx,taus,gains)});els.runBtn.click();